require: rubocop-performance

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.6
  # uncomment if use rails cops
  # TargetRailsVersion: 5.1
