require: rubocop-performance

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"
    - "config/performance.yml"

AllCops:
  TargetRubyVersion: 3.0
  # uncomment if use rails cops
  # TargetRailsVersion: 5.1
  NewCops: enable

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
