version: 2.0

default: &default
  docker:
    - image: circleci/ruby:2.4.1-node-browsers
      environment:
        RACK_ENV: test
        CODECLIMATE_REPO_TOKEN: 4b2a7d452fe78268da978f159e06bfe6a7749aeb875ab3d93ca37dfc799bd3dc
    - image: memcached:1.5-alpine
  working_directory: ~/app

jobs:
  checkout_code:
    <<: *default

    steps:
      - checkout
      - save_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app

  bundle_dependencies:
    <<: *default

    steps:
      - restore_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v2-bundle-{{ .Environment.CIRCLE_BRANCH }}
            - v2-bundle-master
      - run: bundle install --path vendor/bundle
      - run: bundle clean
      - save_cache:
          key: v2-bundle-{{ .Environment.CIRCLE_BRANCH }}
          paths:
            - ~/app/vendor/bundle

  rspec:
    <<: *default

    steps:
      - restore_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v2-bundle-{{ .Environment.CIRCLE_BRANCH }}
      - run: bundle --path vendor/bundle
      - run: bundle exec rspec
      - run: bundle exec codeclimate-test-reporter

  deploy:
    <<: *default

    steps:
      - restore_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: .circleci/heroku_setup.sh
      - add_ssh_keys:
          fingerprints:
            - "9a:82:fa:fa:35:d4:ea:5f:c5:27:ae:ee:ad:e7:33:5b"
      - run: .circleci/heroku_deploy.sh

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - rspec:
          requires:
            - bundle_dependencies
      - deploy:
          requires:
            - rspec
          filters:
            branches:
              only: master
