version: 2.0

default: &default
  docker:
    - image: circleci/ruby:2.5.1-node-browsers
      environment:
        RACK_ENV: test
        CODECLIMATE_REPO_TOKEN: 4b2a7d452fe78268da978f159e06bfe6a7749aeb875ab3d93ca37dfc799bd3dc
    - image: memcached:1.5-alpine
  working_directory: ~/app

restore_repo_cache_option: &restore_repo_cache_option
  key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}

restore_bundle_cache_option: &restore_bundle_cache_option
  keys:
    - v2-bundle-{{ checksum "Gemfile.lock" }}
    - v2-bundle

jobs:
  checkout_code:
    <<: *default

    steps:
      - checkout
      - save_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app

  bundle_dependencies:
    <<: *default

    steps:
      - restore_cache:
          <<: *restore_repo_cache_option
      - restore_cache:
          <<: *restore_bundle_cache_option
      - run: .circleci/setup_bundle.sh
      - save_cache:
          key: v2-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/app/vendor/bundle

  rspec:
    <<: *default

    steps:
      - restore_cache:
          <<: *restore_repo_cache_option
      - restore_cache:
          <<: *restore_bundle_cache_option
      - run: .circleci/setup_bundle.sh
      - run: bundle exec rspec
      - run: bundle exec codeclimate-test-reporter

  rubocop:
    <<: *default

    steps:
      - restore_cache:
          <<: *restore_repo_cache_option
      - restore_cache:
          <<: *restore_bundle_cache_option
      - run: .circleci/setup_bundle.sh
      - run: bundle exec rubocop

  deploy:
    docker:
      - image: sue445/heroku-cli
    working_directory: /home/circleci/app

    steps:
      - restore_cache:
          <<: *restore_repo_cache_option
      - run: .circleci/heroku_setup.sh
      - add_ssh_keys:
          fingerprints:
            - "9a:82:fa:fa:35:d4:ea:5f:c5:27:ae:ee:ad:e7:33:5b"
      - run: .circleci/heroku_deploy.sh

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - rspec:
          requires:
            - bundle_dependencies
      - rubocop:
          requires:
            - bundle_dependencies
      - deploy:
          requires:
            - rspec
            - rubocop
          filters:
            branches:
              only: master
