version: 2.1

orbs:
  codeclimate: sue445/codeclimate@volatile
  ruby-orbs:   sue445/ruby-orbs@volatile
  heroku:      circleci/heroku@volatile
  slack:       circleci/slack@volatile

executors:
  default:
    docker:
      - image: circleci/ruby:2.7.1-browsers-legacy
        environment:
          RACK_ENV: test
          CC_TEST_REPORTER_ID: 4b2a7d452fe78268da978f159e06bfe6a7749aeb875ab3d93ca37dfc799bd3dc
      - image: memcached:1.5-alpine
    working_directory: ~/app

jobs:
  rspec:
    executor:
      name: default

    steps:
      - checkout
      - ruby-orbs/bundle-install:
          cache_key_prefix: "v3-bundle"
      - codeclimate/with-cc-test-reporter:
          after_build_args: '--coverage-input-type simplecov'
          steps:
            - run: bundle exec rspec
      - slack/notify:
          event: fail
          template: basic_fail_1

  rubocop:
    executor:
      name: default

    steps:
      - checkout
      - ruby-orbs/bundle-install:
          cache_key_prefix: "v3-bundle"
      - run: bundle exec rubocop
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - rspec
      - rubocop
      - heroku/deploy-via-git:
          context: Heroku
          requires:
            - rspec
            - rubocop
          post-deploy:
            - slack/notify:
                event: fail
                template: basic_fail_1
          filters:
            branches:
              only: master
