default:
  servers:
    - "<%= ENV.fetch('MEMCACHED_HOST', 'localhost') %>:11211"
  options:
    namespace: "app-stat-api"
    compress: true
    expires_in: <%= 1.second %>

production:
  servers: <%= ENV["MEMCACHEDCLOUD_SERVERS"]&.split(",") %>
  options:
    expires_in: <%= 5.minutes %>
    username: <%= ENV["MEMCACHEDCLOUD_USERNAME"] %>
    password: <%= ENV["MEMCACHEDCLOUD_PASSWORD"] %>
