- code: cn
  name: 中国
- code: hk/en
  name: Hong Kong
- code: hk
  name: 香港
- code: jp
  name: 日本
- code: kr
  name: 대한민국
- code: nz
  name: New Zealand
- code: tw
  name: 台灣
- code: asia
  name: Other Asia
- code: benl
  name: België
- code: befr
  name: Belgique
- code: dk
  name: Danmark
- code: de
  name: Deutschland
- code: es
  name: España
- code: fr
  name: France
- code: ie
  name: Ireland
- code: it
  name: Italia
- code: nl
  name: Nederland
- code: "no"
  name: Norge
- code: pl
  name: Polska
- code: pt
  name: Portugal
- code: ru
  name: Россия
- code: chde
  name: Schweiz
- code: chfr
  name: Suisse
- code: fi
  name: Suomi
- code: se
  name: Sverige
- code: uk
  name: UK
- code: lae
  name: Antigua & Barbuda
- code: la
  name: Argentina
- code: lae
  name: Barbados
- code: lae
  name: Belize
- code: lae
  name: Bermuda
- code: br
  name: Brasil
- code: lae
  name: British Virgin Islands
- code: lae
  name: Cayman Islands
- code: la
  name: Chile
- code: la
  name: Colombia
- code: lae
  name: Dominica
- code: la
  name: República Dominicana
- code: la
  name: Ecuador
- code: la
  name: El Salvador
- code: lae
  name: Grenada
- code: lae
  name: Guyana
- code: la
  name: Honduras
- code: lae
  name: Jamaica
- code: mx
  name: México
- code: lae
  name: Montserrat
- code: la
  name: Panamá
- code: la
  name: Paraguay
- code: la
  name: Perú
- code: lae
  name: St.Kitts & Nevis
- code: lae
  name: St.Lucia
- code: lae
  name: Suriname
- code: lae
  name: The Bahamas
- code: lae
  name: Trinidad & Tobago
- code: lae
  name: Turks & Caicos
- code: la
  name: Uruguay
- code: la
  name: América Latina y el Caribe
- code: lae
  name: Latin America and the Caribbean
- code: ca/fr
  name: Canada (Français)
- code: lae
  name: Puerto Rico (English)
- code: la
  name: Puerto Rico (español)
- code: us
  name: United States
